### PR TITLE
Upgrade to PHP ^7.2 and and PHPUnit ^8.5

### PR DESCRIPTION
**Pull request by jdreesen**

### CODE REVIEW

**Comment by jdreesen** [comment]
The classes
```php
PHPUnit\Framework\MockObject\Matcher\AnyInvokedCount
PHPUnit\Framework\MockObject\Matcher\Invocation
PHPUnit\Framework\MockObject\Matcher\InvokedAtLeastOnce
```
are marked as `internal` in PHPUnit (which means no BC promise) and moved to 
```php
PHPUnit\Framework\MockObject\Rule\AnyInvokedCount
PHPUnit\Framework\MockObject\Rule\InvocationOrder
PHPUnit\Framework\MockObject\Rule\InvokedAtLeastOnce
```
in PHPUnit 8.5.

I'm not sure how to deal with that.

**Comment by mnapoli** [comment]
Thank you for all that work!

Would it work if we were compatible only with PHPUnit 8.5 and +?

**Comment by mnapoli** [comment]
Oh nevermind, I just saw the diff 😄 

LGTM!

**Comment by mnapoli** [comment]
I just tagged a release.

**Comment by jdreesen** [comment]
Oh, wow, thx for the quick merge/release.

**Pull request merged**
